version: "3"

# services:
#   app:
#     build: .
#     ports:
#       - "8001:8001"
#     volumes:
#       - ./backend:/app/backend
#     image: gifapp
#     working_dir: /app/backend
#     command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
#     depends_on:
#       - db
#     links:
#       - db
#   db:
#     image: "mysql:5.7"
#     environment:
#       - MYSQL_ROOT_PASSWORD=docker
#       - MYSQL_DATABASE=gifapp
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=docker
#       - MYSQL_PORT=3307
#     volumes:
#       - ./data/:/var/lib/mysql
#     ports:
#       - "3307:3306"
#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     ports:
#       - 8090:80
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: yourpassword

services:
  app:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app
    depends_on:
      - api
  api:
    build: ./backend
    working_dir: /app
    restart: unless-stopped
    ports:
      - 5001:8000
    networks:
      - app
    depends_on:
      - db
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 5002:8080
    networks:
      - app
  db:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5003:5432
    networks:
      - app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gifapp
    depends_on:
      - adminer
  db-test:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5004:5432
    networks:
      - app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gifapp_test
    depends_on:
      - adminer
networks:
  app:
